name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  image-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push subspace
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            ghcr.io/kbc8894/subspace:latest
            ghcr.io/kbc8894/subspace:${{ steps.short-sha.outputs.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BUILD_VERSION=v1.3.2-custom
